package no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-12-13T12:39:21.288+01:00
 * Generated source version: 4.0.0
 *
 */
@WebService(targetNamespace = "http://nav.no/tjeneste/virksomhet/behandleArbeidOgAktivitetOppgave/v1", name = "BehandleArbeidOgAktivitetOppgave_v1")
@XmlSeeAlso({no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.informasjon.ObjectFactory.class, no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.feil.ObjectFactory.class, no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.meldinger.ObjectFactory.class, ObjectFactory.class})
public interface BehandleArbeidOgAktivitetOppgaveV1 {

    @WebMethod(action = "http://nav.no/tjeneste/virksomhet/behandleArbeidOgAktivitetOppgave/v1/BehandleArbeidOgAktivitetOppgave_v1/bestillOppgaveRequest")
    @RequestWrapper(localName = "bestillOppgave", targetNamespace = "http://nav.no/tjeneste/virksomhet/behandleArbeidOgAktivitetOppgave/v1", className = "no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.BestillOppgave")
    @ResponseWrapper(localName = "bestillOppgaveResponse", targetNamespace = "http://nav.no/tjeneste/virksomhet/behandleArbeidOgAktivitetOppgave/v1", className = "no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.BestillOppgaveResponse")
    @WebResult(name = "response", targetNamespace = "")
    public no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.meldinger.WSBestillOppgaveResponse bestillOppgave(

        @WebParam(name = "request", targetNamespace = "")
        no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.meldinger.WSBestillOppgaveRequest request
    ) throws BestillOppgaveSikkerhetsbegrensning, BestillOppgaveOrganisasjonIkkeFunnet, BestillOppgavePersonErInaktiv, BestillOppgaveSakIkkeOpprettet, BestillOppgavePersonIkkeFunnet, BestillOppgaveUgyldigInput;

    /**
     * Ping-tjeneste for å sjekke at tjenesten i Arena svarer. 
     */
    @WebMethod(action = "http://nav.no/tjeneste/virksomhet/behandleArbeidOgAktivitetOppgave/v1/BehandleArbeidOgAktivitetOppgave_v1/pingRequest")
    @RequestWrapper(localName = "ping", targetNamespace = "http://nav.no/tjeneste/virksomhet/behandleArbeidOgAktivitetOppgave/v1", className = "no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://nav.no/tjeneste/virksomhet/behandleArbeidOgAktivitetOppgave/v1", className = "no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.PingResponse")
    public void ping()
;
}
