
package no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-12-13T12:39:21.269+01:00
 * Generated source version: 4.0.0
 */

@WebFault(name = "bestillOppgavepersonErInaktiv", targetNamespace = "http://nav.no/tjeneste/virksomhet/behandleArbeidOgAktivitetOppgave/v1")
public class BestillOppgavePersonErInaktiv extends Exception {

    private no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.feil.WSPersonErInaktiv faultInfo;

    public BestillOppgavePersonErInaktiv() {
        super();
    }

    public BestillOppgavePersonErInaktiv(String message) {
        super(message);
    }

    public BestillOppgavePersonErInaktiv(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public BestillOppgavePersonErInaktiv(String message, no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.feil.WSPersonErInaktiv bestillOppgavepersonErInaktiv) {
        super(message);
        this.faultInfo = bestillOppgavepersonErInaktiv;
    }

    public BestillOppgavePersonErInaktiv(String message, no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.feil.WSPersonErInaktiv bestillOppgavepersonErInaktiv, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = bestillOppgavepersonErInaktiv;
    }

    public no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.feil.WSPersonErInaktiv getFaultInfo() {
        return this.faultInfo;
    }
}
