
package no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-12-13T12:39:21.283+01:00
 * Generated source version: 4.0.0
 */

@WebFault(name = "bestillOppgaveugyldigInput", targetNamespace = "http://nav.no/tjeneste/virksomhet/behandleArbeidOgAktivitetOppgave/v1")
public class BestillOppgaveUgyldigInput extends Exception {

    private no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.feil.WSUgyldigInput faultInfo;

    public BestillOppgaveUgyldigInput() {
        super();
    }

    public BestillOppgaveUgyldigInput(String message) {
        super(message);
    }

    public BestillOppgaveUgyldigInput(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public BestillOppgaveUgyldigInput(String message, no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.feil.WSUgyldigInput bestillOppgaveugyldigInput) {
        super(message);
        this.faultInfo = bestillOppgaveugyldigInput;
    }

    public BestillOppgaveUgyldigInput(String message, no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.feil.WSUgyldigInput bestillOppgaveugyldigInput, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = bestillOppgaveugyldigInput;
    }

    public no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.feil.WSUgyldigInput getFaultInfo() {
        return this.faultInfo;
    }
}
