
package no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-12-13T12:39:21.264+01:00
 * Generated source version: 4.0.0
 */

@WebFault(name = "bestillOppgaveorganisasjonIkkeFunnet", targetNamespace = "http://nav.no/tjeneste/virksomhet/behandleArbeidOgAktivitetOppgave/v1")
public class BestillOppgaveOrganisasjonIkkeFunnet extends Exception {

    private no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.feil.WSOrganisasjonIkkeFunnet faultInfo;

    public BestillOppgaveOrganisasjonIkkeFunnet() {
        super();
    }

    public BestillOppgaveOrganisasjonIkkeFunnet(String message) {
        super(message);
    }

    public BestillOppgaveOrganisasjonIkkeFunnet(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public BestillOppgaveOrganisasjonIkkeFunnet(String message, no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.feil.WSOrganisasjonIkkeFunnet bestillOppgaveorganisasjonIkkeFunnet) {
        super(message);
        this.faultInfo = bestillOppgaveorganisasjonIkkeFunnet;
    }

    public BestillOppgaveOrganisasjonIkkeFunnet(String message, no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.feil.WSOrganisasjonIkkeFunnet bestillOppgaveorganisasjonIkkeFunnet, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = bestillOppgaveorganisasjonIkkeFunnet;
    }

    public no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.feil.WSOrganisasjonIkkeFunnet getFaultInfo() {
        return this.faultInfo;
    }
}
