
package no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-12-13T12:39:21.278+01:00
 * Generated source version: 4.0.0
 */

@WebFault(name = "bestillOppgavepersonIkkeFunnet", targetNamespace = "http://nav.no/tjeneste/virksomhet/behandleArbeidOgAktivitetOppgave/v1")
public class BestillOppgavePersonIkkeFunnet extends Exception {

    private no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.feil.WSPersonIkkeFunnet faultInfo;

    public BestillOppgavePersonIkkeFunnet() {
        super();
    }

    public BestillOppgavePersonIkkeFunnet(String message) {
        super(message);
    }

    public BestillOppgavePersonIkkeFunnet(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public BestillOppgavePersonIkkeFunnet(String message, no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.feil.WSPersonIkkeFunnet bestillOppgavepersonIkkeFunnet) {
        super(message);
        this.faultInfo = bestillOppgavepersonIkkeFunnet;
    }

    public BestillOppgavePersonIkkeFunnet(String message, no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.feil.WSPersonIkkeFunnet bestillOppgavepersonIkkeFunnet, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = bestillOppgavepersonIkkeFunnet;
    }

    public no.nav.tjeneste.virksomhet.behandlearbeidogaktivitetoppgave.v1.feil.WSPersonIkkeFunnet getFaultInfo() {
        return this.faultInfo;
    }
}
