
package no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-12-13T12:39:18.394+01:00
 * Generated source version: 4.0.0
 */

@WebFault(name = "behandleKjoerelisteOgOpprettOppgavejournalpostIkkeFunnet", targetNamespace = "http://nav.no/tjeneste/virksomhet/behandleSakOgAktivitet/v1")
public class BehandleKjoerelisteOgOpprettOppgaveJournalpostIkkeFunnet extends Exception {

    private no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.JournalpostIkkeFunnet faultInfo;

    public BehandleKjoerelisteOgOpprettOppgaveJournalpostIkkeFunnet() {
        super();
    }

    public BehandleKjoerelisteOgOpprettOppgaveJournalpostIkkeFunnet(String message) {
        super(message);
    }

    public BehandleKjoerelisteOgOpprettOppgaveJournalpostIkkeFunnet(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public BehandleKjoerelisteOgOpprettOppgaveJournalpostIkkeFunnet(String message, no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.JournalpostIkkeFunnet behandleKjoerelisteOgOpprettOppgavejournalpostIkkeFunnet) {
        super(message);
        this.faultInfo = behandleKjoerelisteOgOpprettOppgavejournalpostIkkeFunnet;
    }

    public BehandleKjoerelisteOgOpprettOppgaveJournalpostIkkeFunnet(String message, no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.JournalpostIkkeFunnet behandleKjoerelisteOgOpprettOppgavejournalpostIkkeFunnet, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = behandleKjoerelisteOgOpprettOppgavejournalpostIkkeFunnet;
    }

    public no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.JournalpostIkkeFunnet getFaultInfo() {
        return this.faultInfo;
    }
}
