
package no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-12-13T12:39:18.386+01:00
 * Generated source version: 4.0.0
 */

@WebFault(name = "behandleKjoerelisteOgOpprettOppgaveugyldigInput", targetNamespace = "http://nav.no/tjeneste/virksomhet/behandleSakOgAktivitet/v1")
public class BehandleKjoerelisteOgOpprettOppgaveUgyldigInput extends Exception {

    private no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.UgyldigInput faultInfo;

    public BehandleKjoerelisteOgOpprettOppgaveUgyldigInput() {
        super();
    }

    public BehandleKjoerelisteOgOpprettOppgaveUgyldigInput(String message) {
        super(message);
    }

    public BehandleKjoerelisteOgOpprettOppgaveUgyldigInput(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public BehandleKjoerelisteOgOpprettOppgaveUgyldigInput(String message, no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.UgyldigInput behandleKjoerelisteOgOpprettOppgaveugyldigInput) {
        super(message);
        this.faultInfo = behandleKjoerelisteOgOpprettOppgaveugyldigInput;
    }

    public BehandleKjoerelisteOgOpprettOppgaveUgyldigInput(String message, no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.UgyldigInput behandleKjoerelisteOgOpprettOppgaveugyldigInput, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = behandleKjoerelisteOgOpprettOppgaveugyldigInput;
    }

    public no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.UgyldigInput getFaultInfo() {
        return this.faultInfo;
    }
}
