
package no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-12-13T12:39:18.403+01:00
 * Generated source version: 4.0.0
 */

@WebFault(name = "behandleKjoerelisteOgOpprettOppgavesakIkkeFunnet", targetNamespace = "http://nav.no/tjeneste/virksomhet/behandleSakOgAktivitet/v1")
public class BehandleKjoerelisteOgOpprettOppgaveSakIkkeFunnet extends Exception {

    private no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.SakIkkeFunnet faultInfo;

    public BehandleKjoerelisteOgOpprettOppgaveSakIkkeFunnet() {
        super();
    }

    public BehandleKjoerelisteOgOpprettOppgaveSakIkkeFunnet(String message) {
        super(message);
    }

    public BehandleKjoerelisteOgOpprettOppgaveSakIkkeFunnet(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public BehandleKjoerelisteOgOpprettOppgaveSakIkkeFunnet(String message, no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.SakIkkeFunnet behandleKjoerelisteOgOpprettOppgavesakIkkeFunnet) {
        super(message);
        this.faultInfo = behandleKjoerelisteOgOpprettOppgavesakIkkeFunnet;
    }

    public BehandleKjoerelisteOgOpprettOppgaveSakIkkeFunnet(String message, no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.SakIkkeFunnet behandleKjoerelisteOgOpprettOppgavesakIkkeFunnet, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = behandleKjoerelisteOgOpprettOppgavesakIkkeFunnet;
    }

    public no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.SakIkkeFunnet getFaultInfo() {
        return this.faultInfo;
    }
}
