
package no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-12-13T12:39:18.338+01:00
 * Generated source version: 4.0.0
 */

@WebFault(name = "behandleKjoerelisteOgOpprettOppgavesikkerhetsbegrensning", targetNamespace = "http://nav.no/tjeneste/virksomhet/behandleSakOgAktivitet/v1")
public class BehandleKjoerelisteOgOpprettOppgaveSikkerhetsbegrensning extends Exception {

    private no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.Sikkerhetsbegrensning faultInfo;

    public BehandleKjoerelisteOgOpprettOppgaveSikkerhetsbegrensning() {
        super();
    }

    public BehandleKjoerelisteOgOpprettOppgaveSikkerhetsbegrensning(String message) {
        super(message);
    }

    public BehandleKjoerelisteOgOpprettOppgaveSikkerhetsbegrensning(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public BehandleKjoerelisteOgOpprettOppgaveSikkerhetsbegrensning(String message, no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.Sikkerhetsbegrensning behandleKjoerelisteOgOpprettOppgavesikkerhetsbegrensning) {
        super(message);
        this.faultInfo = behandleKjoerelisteOgOpprettOppgavesikkerhetsbegrensning;
    }

    public BehandleKjoerelisteOgOpprettOppgaveSikkerhetsbegrensning(String message, no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.Sikkerhetsbegrensning behandleKjoerelisteOgOpprettOppgavesikkerhetsbegrensning, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = behandleKjoerelisteOgOpprettOppgavesikkerhetsbegrensning;
    }

    public no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.Sikkerhetsbegrensning getFaultInfo() {
        return this.faultInfo;
    }
}
