
package no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-12-13T12:39:18.425+01:00
 * Generated source version: 4.0.0
 */

@WebFault(name = "bestillOppgaveMedSaksopplysningsakIkkeOpprettet", targetNamespace = "http://nav.no/tjeneste/virksomhet/behandleSakOgAktivitet/v1")
public class BestillOppgaveMedSaksopplysningSakIkkeOpprettet extends Exception {

    private no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.SakIkkeOpprettet faultInfo;

    public BestillOppgaveMedSaksopplysningSakIkkeOpprettet() {
        super();
    }

    public BestillOppgaveMedSaksopplysningSakIkkeOpprettet(String message) {
        super(message);
    }

    public BestillOppgaveMedSaksopplysningSakIkkeOpprettet(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public BestillOppgaveMedSaksopplysningSakIkkeOpprettet(String message, no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.SakIkkeOpprettet bestillOppgaveMedSaksopplysningsakIkkeOpprettet) {
        super(message);
        this.faultInfo = bestillOppgaveMedSaksopplysningsakIkkeOpprettet;
    }

    public BestillOppgaveMedSaksopplysningSakIkkeOpprettet(String message, no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.SakIkkeOpprettet bestillOppgaveMedSaksopplysningsakIkkeOpprettet, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = bestillOppgaveMedSaksopplysningsakIkkeOpprettet;
    }

    public no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.SakIkkeOpprettet getFaultInfo() {
        return this.faultInfo;
    }
}
