
package no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-12-13T12:39:18.410+01:00
 * Generated source version: 4.0.0
 */

@WebFault(name = "bestillOppgaveMedSaksopplysningsikkerhetsbegrensning", targetNamespace = "http://nav.no/tjeneste/virksomhet/behandleSakOgAktivitet/v1")
public class BestillOppgaveMedSaksopplysningSikkerhetsbegrensning extends Exception {

    private no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.Sikkerhetsbegrensning faultInfo;

    public BestillOppgaveMedSaksopplysningSikkerhetsbegrensning() {
        super();
    }

    public BestillOppgaveMedSaksopplysningSikkerhetsbegrensning(String message) {
        super(message);
    }

    public BestillOppgaveMedSaksopplysningSikkerhetsbegrensning(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public BestillOppgaveMedSaksopplysningSikkerhetsbegrensning(String message, no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.Sikkerhetsbegrensning bestillOppgaveMedSaksopplysningsikkerhetsbegrensning) {
        super(message);
        this.faultInfo = bestillOppgaveMedSaksopplysningsikkerhetsbegrensning;
    }

    public BestillOppgaveMedSaksopplysningSikkerhetsbegrensning(String message, no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.Sikkerhetsbegrensning bestillOppgaveMedSaksopplysningsikkerhetsbegrensning, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = bestillOppgaveMedSaksopplysningsikkerhetsbegrensning;
    }

    public no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.Sikkerhetsbegrensning getFaultInfo() {
        return this.faultInfo;
    }
}
