
package no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-12-13T12:39:18.431+01:00
 * Generated source version: 4.0.0
 */

@WebFault(name = "bestillOppgaveMedSaksopplysningpersonIkkeFunnet", targetNamespace = "http://nav.no/tjeneste/virksomhet/behandleSakOgAktivitet/v1")
public class BestillOppgaveMedSaksopplysningPersonIkkeFunnet extends Exception {

    private no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.PersonIkkeFunnet faultInfo;

    public BestillOppgaveMedSaksopplysningPersonIkkeFunnet() {
        super();
    }

    public BestillOppgaveMedSaksopplysningPersonIkkeFunnet(String message) {
        super(message);
    }

    public BestillOppgaveMedSaksopplysningPersonIkkeFunnet(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public BestillOppgaveMedSaksopplysningPersonIkkeFunnet(String message, no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.PersonIkkeFunnet bestillOppgaveMedSaksopplysningpersonIkkeFunnet) {
        super(message);
        this.faultInfo = bestillOppgaveMedSaksopplysningpersonIkkeFunnet;
    }

    public BestillOppgaveMedSaksopplysningPersonIkkeFunnet(String message, no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.PersonIkkeFunnet bestillOppgaveMedSaksopplysningpersonIkkeFunnet, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = bestillOppgaveMedSaksopplysningpersonIkkeFunnet;
    }

    public no.nav.tjeneste.virksomhet.behandlesakogaktivitet.v1.feil.PersonIkkeFunnet getFaultInfo() {
        return this.faultInfo;
    }
}
